// THIS FILE IS AUTO-GENERATED by scripts/scaffold-client.ts
// Regenerate: cd frontend && npx tsx ../scripts/scaffold-client.ts
// Source IDL: src/assets/agent_colosseum.idl
// Custom helpers should go in a separate file (e.g., sails-helpers.ts)

import type { GearApi } from "@gear-js/api";
import idlRaw from "@/assets/agent_colosseum.idl?raw";

let cachedSails: Promise<unknown> | null = null;
let cachedApi: GearApi | null = null;

export async function initSails(api: GearApi) {
  // Invalidate cache if api instance changed (fixes stale connection after reconnect)
  if (cachedSails && cachedApi !== api) {
    cachedSails = null;
  }
  if (!cachedSails) {
    cachedApi = api;
    cachedSails = (async () => {
      const [{ Sails }, { SailsIdlParser }] = await Promise.all([
        import("sails-js"),
        import("sails-js-parser"),
      ]);
      const parser = await SailsIdlParser.new();
      const sails = new Sails(parser);
      sails.setApi(api);
      sails.parseIdl(idlRaw);

      const programId = import.meta.env.VITE_PROGRAM_ID;
      if (programId) {
        sails.setProgramId(programId as `0x${string}`);
      }

      return sails;
    })().catch((err) => {
      cachedSails = null;
      cachedApi = null;
      throw err;
    });
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return cachedSails as Promise<any>;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function getService(sails: any): any {
  return sails?.services?.AgentColosseum ?? sails?.services?.agentcolosseum;
}

// -- Queries --

export async function queryAgent(api: GearApi, agent_id: string): Promise<unknown | null> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.GetAgent(agent_id).call();
}

export async function queryConfig(api: GearApi): Promise<[number, boolean, string]> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.GetConfig().call();
}

export async function queryMatch(api: GearApi, match_id: string): Promise<unknown | null> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.GetMatch(match_id).call();
}

export async function queryListActiveMatches(api: GearApi): Promise<unknown[]> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.ListActiveMatches().call();
}

export async function queryListAgents(api: GearApi, offset: number, limit: number): Promise<unknown[]> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.ListAgents(offset, limit).call();
}

export async function queryListMatches(api: GearApi, offset: number, limit: number): Promise<unknown[]> {
  const sails = await initSails(api);
  const service = getService(sails);
  return service.queries.ListMatches(offset, limit).call();
}

// -- Transactions --

export async function txClaimWinnings(
  api: GearApi,
  account: string,
  match_id: string,
  signer?: unknown
): Promise<string> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.ClaimWinnings(match_id);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txCreateMatch(
  api: GearApi,
  account: string,
  stake: string,
  signer?: unknown
): Promise<string> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.CreateMatch(stake);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txJoinMatch(
  api: GearApi,
  account: string,
  match_id: string,
  signer?: unknown
): Promise<null> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.JoinMatch(match_id);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txRegisterAgent(
  api: GearApi,
  account: string,
  name: string,
  body_parts: unknown,
  strategy_hash: number[],
  strategy_url: string,
  signer?: unknown
): Promise<string> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.RegisterAgent(name, body_parts, strategy_hash, strategy_url);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txSetBattleResult(
  api: GearApi,
  account: string,
  match_id: string,
  winner: string,
  timeline_hash: number[],
  signer?: unknown
): Promise<null> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.SetBattleResult(match_id, winner, timeline_hash);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txSetPaused(
  api: GearApi,
  account: string,
  paused: boolean,
  signer?: unknown
): Promise<null> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.SetPaused(paused);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txSetProtocolFee(
  api: GearApi,
  account: string,
  fee_bps: number,
  signer?: unknown
): Promise<null> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.SetProtocolFee(fee_bps);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

export async function txUpdateAgent(
  api: GearApi,
  account: string,
  name: string | null,
  body_parts: unknown | null,
  strategy_hash: number[] | null,
  strategy_url: string | null,
  signer?: unknown
): Promise<null> {
  const sails = await initSails(api);
  const service = getService(sails);
  const tx = service.functions.UpdateAgent(name, body_parts, strategy_hash, strategy_url);
  const result = await tx
    .withAccount(account, signer ? { signer } : undefined)
    .calculateGas()
    .then(() => tx.signAndSend());
  return result.response();
}

/** Get the raw IDL text for the debug panel. */
export function getIdlText(): string {
  return idlRaw;
}
